# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: mkdir ~/junit
      - run:
          name: Run unit tests
          command: ./node_modules/mocha/bin/mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
workflows:
 build-test-deploy:
  jobs:
    - build-and-test