# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:12
    steps:
     - checkout
     - run:
        name: Install dependencies
        command: npm install
     - run: 
        name: Run Unit Tests
        command: npm run test
